name: run-tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3]
        laravel: [10]
        stability: [prefer-dist]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pcov, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, :psr
          ini-values: memory_limit=512M
          coverage: none
          
      - name: Install dependencies
        run: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-interaction && composer update

      - name: Install paratest
        run: composer require brianium/paratest

      - name: Run Unit Tests
        run: php ./vendor/bin/paratest --no-coverage --processes=1
